require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/lines", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Line. As you add validations to Line, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Line.create! valid_attributes
      get lines_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      line = Line.create! valid_attributes
      get line_url(line)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_line_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      line = Line.create! valid_attributes
      get edit_line_url(line)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Line" do
        expect {
          post lines_url, params: { line: valid_attributes }
        }.to change(Line, :count).by(1)
      end

      it "redirects to the created line" do
        post lines_url, params: { line: valid_attributes }
        expect(response).to redirect_to(line_url(Line.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Line" do
        expect {
          post lines_url, params: { line: invalid_attributes }
        }.to change(Line, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post lines_url, params: { line: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested line" do
        line = Line.create! valid_attributes
        patch line_url(line), params: { line: new_attributes }
        line.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the line" do
        line = Line.create! valid_attributes
        patch line_url(line), params: { line: new_attributes }
        line.reload
        expect(response).to redirect_to(line_url(line))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        line = Line.create! valid_attributes
        patch line_url(line), params: { line: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested line" do
      line = Line.create! valid_attributes
      expect {
        delete line_url(line)
      }.to change(Line, :count).by(-1)
    end

    it "redirects to the lines list" do
      line = Line.create! valid_attributes
      delete line_url(line)
      expect(response).to redirect_to(lines_url)
    end
  end
end
